config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: "tasks#index"
  get 'sessions/new'
  get "search" => "tasks#search"
  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  enum priority: { high: 0, middle: 1, low: 2, other:3 }
  validates :name, presence: true
  validates :content, presence: true
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  belongs_to :user
  
  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
      .status_is(search_params[:status])

  end
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :status_is, -> (status) { where(status: status) if status.present? }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_login?
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @search_params = task_search_params
    @tasks = Task.all
    if params[:label_id].present?
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) 
    else
      @tasks = Task.search(@search_params)
    end
      @tasks = @tasks.order(params[:sort]).page(params[:page]).per(5)
    end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end
    
  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :status, :task_limit, :content, :created_at, :priority, :user_id,
    { label_ids: [] })
  end

  def task_search_params
    params.fetch(:search, {}).permit(:name, :status, :label_id)
  end

  def check_login?
    unless current_user.presence
      redirect_to new_session_path, notice: 'You should log in.'
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,["Not Started","Undertake","Complete"] %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>

  <div class="field">
    <%= form.label :task_limit %>
    <%= form.date_field :task_limit, value: Time.now.strftime("%Y年%m月%d日") %>
  </div>
  
  <div class="field">
    <h3>Label</h3>
    <label class="checkbox-inline">
      <%= form.collection_check_boxes(:label_ids, Label.all, :id, :title) %>
    </label>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tasks</h1>

<!--ここから検索フォーム-->
<div class="search-form" style="padding: 10px; margin-bottom: 10px; border: 1px dotted #333333; width: 300px">
  <h3>Task Search</h3>
  <%= form_with(scope: :search, url: tasks_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label(:name, Task.human_attribute_name(:name)) %>
      <%= f.text_field :name, value: @search_params[:name] %>
    </div>
    <div class="field">
      <%= f.label(:status, Task.human_attribute_name(:status)) %>
      <%= f.select(:status,["","Not Started","Undertake","Complete"] ,value: @search_params[:status])%>
    </div>
    <div class="actions">
      <%= f.submit "Search" %>
    </div>
  <% end %>
  <div class = "search-cell" >
    <%= form_with url: tasks_path, method: :get, local: true do |form| %>
      <%= form.label(:label_id) %>
      <%= form.select("label_id", Label.pluck(:title, :id), { include_blank: true }) %>
      <%= form.submit 'search', name: nil %>
      <%= link_to "Create New Label", new_label_path %>
    <% end %>
  </div>
</div>

<!--ここからデータの表示-->
<% def linkage(column, direction) %>
<% arrow = "▲" %>
<% if direction == "desc" %>
<% arrow = "▼" %>
<% end %>
  <%= link_to arrow, sort: column + " " + direction %>
<% end %>

<table class="table table-striped" >
  <thead>
    <tr>
      <th class = "priority-cell">Priority<%= link_to "▲", sort: "priority asc", class:"sort01" %><%= link_to "▼", sort: "priority desc", class:"sort02" %></th>
      <th>User</th>
      <th>Name <%= linkage("name","asc") %><%= linkage("name","desc") %></th>
      <th>Status <%= linkage("status","asc") %><%= linkage("status","desc") %></th>
      <th>Created <%= linkage("created_at","asc") %><%= linkage("created_at","desc") %></th>
      <th>Limit <%= linkage("task_limit","asc") %><%= linkage("task_limit","desc") %></th>
      <th>Content <%= linkage("content","asc") %><%= linkage("content","desc") %></th>
      <th>Labels </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.user_id == current_user.id %>
        <tr>
          <td><%= task.priority %></td>
          <td><%= task.user.name %></td>
          <td><%= task.name %></td>
          <td><%= task.status %></td>
          <td><%= task.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= task.task_limit.strftime("%Y-%m-%d") %></td>
          <td><%= task.content %></td>
          <td><% task.labels.each do |label| %>
                <%= label.title %>, 
              <% end %></td>
          <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
<br>
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @task.name %></h1>
<br>
<p>
  <strong>User:</strong>
  <%= @task.user.name %>
</p>

<p style="color:red">
  <strong>Limit:</strong>
  <%= @task.task_limit.strftime("%Y-%m-%d")  %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Created:</strong>
  <%= @task.created_at.strftime("%Y-%m-%d")  %>
</p>

<p>
  <strong>Labels:</strong>
  <% @task.labels.each do |label| %>
    <%= label.title %>, 
  <% end %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>