config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: "tasks#index"
  get 'sessions/new'
  get "search" => "tasks#search"
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :admin_presence
  before_update :admin_presence
  has_many :tasks, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
  uniqueness: true
  has_secure_password
  
  def task_count
    if tasks.loaded?
      tasks.size
    else
      tasks.count
    end
  end
  def admin_presence
    if User.where(admin: true).count <= 1 && self.admin == true
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user_check

  def index
    @users = User.all
  end

  def show
    @search_params = task_search_params
    @tasks = Task.search(@search_params).order(params[:sort]).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :admin, :password, :password_confirmation, :email)
  end

  def task_params
    params.require(:task).permit(:name, :status, :label, :task_limit, :content, :created_at, :priority, :user_id)
  end

  def task_search_params
    params.fetch(:search, {}).permit(:name, :status)
  end

  def admin_user_check
    if current_user == nil ||current_user.admin == false
      redirect_to root_path, notice: "You are not administrator."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :user_check, only:[:show, :edit, :destroy]

  def index
    @users = User.all
  end

  def show
    @search_params = task_search_params
    @tasks = Task.search(@search_params).order(params[:sort]).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if User.where(admin: true).count.zero?
      @user.admin = true
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to  { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

  def task_params
    params.require(:task).permit(:name, :status, :label, :task_limit, :content, :created_at, :priority, :user_id)
  end

  def task_search_params
    params.fetch(:search, {}).permit(:name, :status)
  end

  def user_check
    if current_user.id != @user.id && current_user.admin == false
      redirect_to users_url, notice: "You could not access this page."
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :admin %>
    <%= form.select :admin,["false","true"] %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', [:admin, @user] %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Page</h1>

<table class="table table-striped" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th>E-mail</th>
      <th>Tasks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.admin %></td>
        <td><%= user.email %></td>
        <td><%= user.task_count %>
        <td><%= link_to 'Show', [:admin, user] %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>

<h1><%= @user.name %>'s Page</h1>
<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>
<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>
<!--ここから検索フォーム-->
<div class="search-form" style="padding: 10px; margin-bottom: 10px; border: 1px dotted #333333; width: 300px">
  <h3>Task Search</h3>
  <%= form_with(scope: :search, url: tasks_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label(:name, Task.human_attribute_name(:name)) %>
      <%= f.text_field :name, value: @search_params[:name] %>
    </div>
    <div class="field">
      <%= f.label(:status, Task.human_attribute_name(:status)) %>
      <%= f.select(:status,["","Not Started","Undertake","Complete"] ,value: @search_params[:status])%>
    </div>
    <div class="actions">
      <%= f.submit "Search" %>
    </div>
  <% end %>
  <%= form_with url: tasks_path, method: :get, local: true do |form| %>
    <%= form.select("label_id", Label.pluck(:title, :id), { include_blank: true }) %>
    <%= form.label(:label_id) %>
    <%= form.submit 'Search', name: nil %>
    <%= link_to "Create New Label", new_label_path %>
  <% end %>
</div>

<!--ここからデータの表示-->
<% def linkage(column, direction) %>
  <% arrow = "▲" %>
  <% if direction == "desc" %>
    <% arrow = "▼" %>
  <% end %>
  <%= link_to arrow, sort: column + " " + direction %>
<% end %>

<table class="table table-striped" >
  <thead>
    <tr>
      <th class = "priority-cell">Priority<%= link_to "▲", sort: "priority asc", class:"sort01" %><%= link_to "▼", sort: "priority desc", class:"sort02" %></th>
      <th>User</th>
      <th>Name <%= linkage("name","asc") %><%= linkage("name","desc") %></th>
      <th>Status <%= linkage("status","asc") %><%= linkage("status","desc") %></th>
      <th>Label <%= linkage("label","asc") %><%= linkage("label","desc") %></th>
      <th>Created <%= linkage("created_at","asc") %><%= linkage("created_at","desc") %></th>
      <th>Limit <%= linkage("task_limit","asc") %><%= linkage("task_limit","desc") %></th>
      <th>Content <%= linkage("content","asc") %><%= linkage("content","desc") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.user_id == @user.id %>
        <tr>
          <td><%= task.priority %></td>
          <td><%= task.user.name %></td>
          <td><%= task.name %></td>
          <td><%= task.status %></td>
          <td><%= task.label %></td>
          <td><%= task.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= task.task_limit.strftime("%Y-%m-%d") %></td>
          <td><%= task.content %></td>
          <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %> |
<%= link_to 'New Task', new_task_path %>